#!/usr/bin/env bash

source "$(cd "$(dirname "$0")" && pwd)/_shared.sh"

targets=("$@")

if [[ ${#targets[@]} -eq 0 ]]; then
	targets=(.)
fi

run pnpm exec prettier --config ./prettier.config.mjs --write "${targets[@]}"